### ISSUE TITLE
what is the function of  norm_vectors ?

### ISSUE THREAD

**Issue by imliuan** [CalabreseLab/seekr#1]
Hi,
what is the function of  norm_vectors ?
is the norm pearson results  more accuracy than nonstandardized?

my lncRNA does not have a complete genome annotation,
how should I do to norm my vectors ?

thanks

**Comment by Jessime** [comment]
Hello!

> is the norm pearson results more accuracy than nonstandardized?

In virtually all of our experiments, we found that normalization was a more accurate predictor of the biological properties we were interested in. If you have time, it could be worthwhile to try both normalized and unnormalized kmers, and see which works best for your data.

> my lncRNA does not have a complete genome annotation,
> how should I do to norm my vectors ?

Good question! You have a few options:

1. You could normalized to the incomplete annotation. This is likely still better than doing no normalization.
2. You could normalize to a closely related species that has a more fully annotated transcriptome. The Ulitsky group maintains a nice [set of annotations](http://www.weizmann.ac.il/Biological_Regulation/IgorUlitsky/PLAR).
3. You could fall back to normalizing to some well known annotation like human or mouse. 

Hope this helps!

**Comment by imliuan** [comment]
thank you very much :)
