### ISSUE TITLE
module 'networkx' has no attribute 'connected_component_subgraphs'

### ISSUE THREAD

**Issue by zengXchao** [CalabreseLab/seekr#12]
Have you noticed that 'connected_component_subgraphs' is removed in 'networkx' version 2.4?

**Comment by Jessime** [comment]
I have; `networkx` is specifically pinned to avoid this problem until I get a chance to fix it.

https://github.com/CalabreseLab/seekr/blob/master/setup.py#L40

**Comment by zengXchao** [comment]
@Jessime I think I met this problem because I installed **seekr** via **pip** as you suggested in the README.
And I fixed it by replacing 
`subgraphs = list(networkx.connected_component_subgraphs(self.graph))`
with
`subgraphs =[self.graph.subgraph(c) for c in networkx.connected_components(self.graph)]`
in the **graph.py**.
Hope this helps.

**Comment by Jessime** [comment]
It does help, thank you! I haven't made a new pypi package yet, but your fix is now pushed to the repo.
