### ISSUE TITLE
Broken links

### ISSUE THREAD

**Issue by erisemberg** [CalabreseLab/seekr#17]
seekr.org takes me to an 'Internal Server Error' page. Also, the link below takes me to a 'Not Found' page. 

![image](https://user-images.githubusercontent.com/69211470/89321823-672e3d00-d651-11ea-8236-cc547c3ece95.png)

**Comment by Jessime** [comment]
Thanks for taking the time to point these out! 

seekr.org likely isn't going to be supported moving forward, so I've removed it from the README (at least for now).

But I've updated the second link you pointed out to https://github.com/CalabreseLab/seekr/blob/master/seekr/tests/data/example_2mers.csv
