### ISSUE TITLE
"example" section of seekr_kmer_counts needs small update

### ISSUE THREAD

**Issue by jmcalabr** [CalabreseLab/seekr#18]
seekr_kmer_counts --help

prints this as one example usage:
"You can change also change the size of the kmer you're using, and prevent normalization:
    $ seekr_kmer_counts rnas.fa -o out.csv -k 4 -uc -us -nl "

The -nl option has been depracated and replaced with "-l none"

Thank you,
Mauro

**Comment by Jessime** [comment]
Updated, and also caught it in another location. See changes in [this commit](https://github.com/CalabreseLab/seekr/commit/022fdd9c794d2197a28fdffb22596c1f8f85f47c).

I'm not going to go through the process of creating a new release, so you won't see these changes immediately reflected. But the next time we have a bug or feature update, I'll do a release and these changes will be included.

**Comment by jmcalabr** [comment]
Fantastic – thanks Jessime
