### ISSUE TITLE
issue with --log2 compatibility in seekr_domain_pearson?

### ISSUE THREAD

**Issue by jmcalabr** [CalabreseLab/seekr#19]
Hi Jessime,

I am no longer able to run seekr_domain_pearson. I may be totally off base with this, but I think it's a small error due to the changes made in the way we specify the method of log-transformation.

Currently, most of seekr is using:
	-l {pre,post,none}, --log2 {pre,post,none}

But, I am not certain that the analogous changes were made in seekr_domain_pearson:

  	-l LOG2, --log2 LOG2  Choose a value of 1,2, or 3 for different log
                        transformation options (default: None)

Accordingly, when I run seekr_domain_pearson, I get the following error:

  File "/Users/maurocalabrese/anaconda3/lib/python3.7/site-packages/seekr/kmer_counts.py", line 121, in __init__
    raise TypeError(f'log2 must be one of {list(Log2)}')
TypeError: log2 must be one of [<Log2.pre: 1>, <Log2.post: 2>, <Log2.none: 3>]

Feel free to contact Dan about this too if that would help (or I can contact him).

Thanks and hope you are well,
Mauro

**Comment by Jessime** [comment]
Looks like your diagnosis was right on the money. Give `1.5.1` a whirl. 

```
pip install seekr --upgrade
```

I don't think I'll have time for this any time soon, but it's worth noting that `seekr_domain_pearson` doesn't have any command line tests like a lot of the rest of the functionality does. It might be worth expanding on https://github.com/CalabreseLab/seekr/blob/master/seekr/tests/integration.sh

**Comment by jmcalabr** [comment]
Thanks Jessime for being so responsive!

The original error was fixed but it looks like we may have uncovered other underlying issues – I get two different errors if I run the function with different sets of options. Caveat is this is the first time I am actually trying seekr_domain_pearson, so possibly the issues have been here all along. Or maybe Dan broke something just before he left?

In either case, I appreciate the help! Different labs have started reaching out to us about seekr, and we are now in the position to use the package more ourselves as well, so thanks for your foresight in coding all of this!

(and FYI that methods article we wrote 1.75 years ago may be published in December…)

Mauro


Default:
seekr_norm_vectors gencode.vM17.lncRNA_transcripts.fa -k 5 -l pre
seekr_domain_pearson mA.fa test.fa.txt mean.npy std.npy -k 5 -l pre

Error:

  File "/Users/maurocalabrese/anaconda3/lib/python3.7/site-packages/seekr/kmer_counts.py", line 175, in get_counts

    self.counts = np.zeros([len(self.seqs), self.alpha_len**self.k], dtype=np.float32)

TypeError: object of type 'NoneType' has no len()

Change “slide”:
seekr_norm_vectors gencode.vM17.lncRNA_transcripts.fa -k 5 -l pre
seekr_domain_pearson mA.fa test.fa.txt mean.npy std.npy -k 5 -l pre -s 250


  File "/Users/maurocalabrese/anaconda3/lib/python3.7/site-packages/seekr/kmer_counts.py", line 175, in get_counts

    self.counts = np.zeros([len(self.seqs), self.alpha_len**self.k], dtype=np.float32)

TypeError: object of type 'NoneType' has no len()

**Comment by Jessime** [comment]
For the first error, I hadn't caught it because I never ran `seekr_domain_pearson` without passing `--reference_path`, which you need to calculate percentiles. I'd suggest passing `--reference_path` or `-rp`. 

For the second error, I was just passing the wrong type from the command line. Just for record keeping, the error with `-s` was:

```
Traceback (most recent call last):
  File "/Users/jessime.kirk/Desktop/v_tmp/.venv/bin/seekr_domain_pearson", line 8, in <module>
    sys.exit(console_domain_pearson())
  File "/Users/jessime.kirk/Desktop/v_tmp/.venv/lib/python3.7/site-packages/seekr/console_scripts.py", line 676, in console_domain_pearson
    args.slide,
  File "/Users/jessime.kirk/Desktop/v_tmp/.venv/lib/python3.7/site-packages/seekr/console_scripts.py", line 619, in _run_domain_pearson
    domain_pearson.run()
  File "/Users/jessime.kirk/Desktop/v_tmp/.venv/lib/python3.7/site-packages/seekr/pearson.py", line 333, in run
    r_values.append(self.compare_query_target(query_counts, target_header, target))
  File "/Users/jessime.kirk/Desktop/v_tmp/.venv/lib/python3.7/site-packages/seekr/pearson.py", line 253, in compare_query_target
    target_counts = self.get_target_tile_counts(target)
  File "/Users/jessime.kirk/Desktop/v_tmp/.venv/lib/python3.7/site-packages/seekr/pearson.py", line 230, in get_target_tile_counts
    for i in range(0, upper, self.slide):
TypeError: 'str' object cannot be interpreted as an integer
```

Anyway, both are fixed now.

By the way, if anyone in the lab is using seekr regularly and wants to add formal tests to `DomainPearson`, I'd be happy to review a PR. 😄

**Comment by Jessime** [comment]
@jmcalabr, have you had a chance to verify that these bugs are fixed? I'll go ahead and close this issue if so.

**Comment by jmcalabr** [comment]
Yup! Everything is working as far as I can tell!
Mauro
