### ISSUE TITLE
Namespace error log2

### ISSUE THREAD

**Issue by kmothera** [CalabreseLab/seekr#2]
Hello,

I am trying to run seekr_kmer_counts on the default example.fa data using the commands specified but I'm getting errors when executing. I've tried running kmer_counts with output set to CSV and binary and still get the same error.  This was installed within a python3.7 virtual environment. Other scripts like the download_gencode and norm_vectors have worked, however. 

`seekr_kmer_counts example.fa -o test.csv -k2 -b -lb`

I get the following error:
> Traceback (most recent call last):
  File "/virtualenv/bin/seekr_kmer_counts", line 10, in <module>
    sys.exit(console_kmer_counts())
  File "/virtualenv/lib/python3.7/site-packages/seekr/console_scripts.py", line 226, in console_kmer_counts
    args.unstandardized, args.log2, args.label, args.mean_vector, args.std_vector)
AttributeError: 'Namespace' object has no attribute 'log2'

Any help would be much appreciated!

**Comment by Jessime** [comment]
Hello, and thanks for letting us know about this issue. I've pushed a fix for it, so try running:

```
$ pip install seekr --upgrade
```

And then try: 

```
$ seekr_kmer_counts example.fa -o test.csv -k 2 -lb
```

Let us know if you run into any more issues!

**Comment by kmothera** [comment]
Thanks! kmer_counts appears to be working.

**Comment by Jessime** [comment]
Great, glad to hear it.
