### ISSUE TITLE
log2 parameter of kmer_count.BasicCounter in the python modul

### ISSUE THREAD

**Issue by MaxFeussner** [CalabreseLab/seekr#21]
Hi,
i was wondering what value or variable i should put as parameter? Because in the preprint of the Method paper it is stated to use this line of code if no log2 transformation should be done.
```
counter = kmer_counts.BasicCounter(fasta01_path, log2=False)
```
But this throws the error:

Traceback (most recent call last):
  File "/home/max/PycharmProjects/Seekr_test/human_kmer_communities.py", line 16, in <module>
    counter = kmer_counts.BasicCounter(fasta01_path, log2=False)
  File "/home/max/PycharmProjects/Seekr_test/venv/lib/python3.8/site-packages/seekr/kmer_counts.py", line 134, in __init__
    raise TypeError(f"log2 must be one of {list(Log2)}")
TypeError: log2 must be one of [<Log2.pre: 1>, <Log2.post: 2>, <Log2.none: 3>]

I have seen this error before in one of the closed Issues but i could not solve my problem with the answers i have found there. I would be glad if you could help me with this problem and Im really sorry if i have overseen anything that could have solved this problem.

Have a nice Day and thanks for the nice program
Maximilian Feussner

**Comment by Jessime** [comment]
Hey, @MaxFeussner!

This functionality has been changed since the Method paper was published, so that line of code is a little out of date. If you didn't want a log2 transform, it would look like:

```
counter = kmer_counts.BasicCounter(fasta01_path, log2=kmer_counts.Log2.none)
```

Here's where you can find the `Enum` which describes the options you can pass to the `log2` parameter:

https://github.com/CalabreseLab/seekr/blob/master/seekr/kmer_counts.py#L45

**Comment by MaxFeussner** [comment]
Thank you very much. This advice helped me a lot.

**Comment by Jessime** [comment]
Great! I'm going to close this issue, but feel free to create new ones if you run into additional difficulty.
